### ISSUE TITLE
Missed Translations. 

### ISSUE THREAD

**Issue by EndrII** [snooppr/shotstars#1]
Please add English translation into your tool.

**Comment by snooppr** [comment]
I'll look into this.

**Comment by snooppr** [comment]
@EndrII I translated the source code into English and posted new [builds](https://github.com/snooppr/shotstars/releases). You can check and I will close this issue. Thank you.

**Comment by EndrII** [comment]
> @EndrII I translated the source code into English and posted new [builds](https://github.com/snooppr/shotstars/releases). You can check and I will close this issue. Thank you.

Thank you )
